#!/bin/sh

## some exports
# kitty
# export KITTY_ENABLE_WAYLAND=1

# firefox
export MOZ_ENABLE_WAYLAND=1

# fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export SDL_IM_MODULE=fcitx5
export XMODIFIERS="@im=fcitx5"

# ibus
export GLFW_IM_MODULE="ibus"

# qt5
export QT_QPA_PLATFORMTHEME=qt5ct

# swap ctrl and caps
# export XKB_DEFAULT_OPTIONS=caps:ctrl

# gtk stuff
export GTK_USE_PORTAL=0

# cursor
export XCURSOR_THEME=Future-cursors
export XCURSOR_SIZE=16

## Keybinds
# Setting the Mod key
mod="Mod4"

# define device name
touchpad="pointer-1267-12596-ASUE140A:00_04F3:3134_Touchpad"
## Applications
# kitty
# riverctl map normal $mod Return spawn "KITTY_ENABLE_WAYLAND=1 kitty"
riverctl map normal $mod Return spawn "kitty"

# Mod+Q to close the focused view
riverctl map normal $mod Q close

#  emacsclient
riverctl map normal $mod A spawn "emacsclient -c"

# wifi4wofi https://github.com/fearlessgeekmedia/wifi4wofi
riverctl map normal $mod W spawn "wifi4wofi"

# Mod d for dmenu
riverctl map normal $mod R spawn "wofi --show drun"

# Mod e for file manager
# riverctl map normal $mod E spawn "nemo"
riverctl map normal $mod D spawn "dolphin"

# Browser
# riverctl map normal $mod E spawn "MOZ_ENABLE_WAYLAND=1 firefox"
riverctl map normal $mod E spawn "firefox"

# pavucontrol
riverctl map normal $mod V spawn "pavucontrol"

# copy screenshot to clipboard
#riverctl map normal $mod S spawn "grim - | wl-copy"
riverctl map normal $mod S spawn "grimshot copy output"
riverctl map normal $mod+Shift S spawn "grimshot copy area"

riverctl map normal $mod F5 spawn "light -A 5"
riverctl map normal $mod F6 spawn "ligth -U 5"

## some touchpad settings
# Pointer Accel v2.0x
# riverctl input $touchpad pointer-accel 0.6
# riverctl input $touchpad 0.6

# Enable tap v2.0x
riverctl input $touchpad tap enabled

# Enable middle click
riverctl input $touchpad middle-emulation enabled

# Enable natural-scrolling
riverctl input $touchpad natural-scroll enabled

## Window Management
# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+Q to exit river
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
# riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal $mod+Shift M send-layout-cmd rivertile "main-ratio 0.5"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"
riverctl map normal $mod+Shift N send-layout-cmd rivertile "main-count 1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal -100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

## Workspaces
# Mod+0 to focus all tags Mod+Shift+0 to tag focused view with all tags
for i in $(seq 1 9); do
	tags=$((1 << ($i - 1)))

	# Mod+[1-9] to focus tag [0-8]
	riverctl map normal $mod $i set-focused-tags $tags

	# Mod+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal $mod+Shift $i set-view-tags $tags

	# Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
	riverctl map normal $mod+Control $i toggle-focused-tags $tags

	# Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
	riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Focus all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Toggle Float
riverctl map normal $mod+Shift Space toggle-float
riverctl map normal $mod o default-layout float
riverctl map normal $mod i default-layout rivertile

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Focus follows mouse
riverctl focus-follows-cursor disabled

# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked; do
	# Eject the optical drive
	riverctl map $mode None XF86Eject spawn 'eject -T'

	# Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
	riverctl map $mode None XF86AudioRaiseVolume spawn 'amixer set "Master" 5%+'
	riverctl map $mode None XF86AudioLowerVolume spawn 'amixer set "Master" 5%-'
	riverctl map $mode None XF86AudioMute spawn 'amixer set "Master" toggle'

	# Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext spawn 'playerctl next'

	# Control screen backlight brighness with light (https://github.com/haikarainen/light)
	riverctl map $mode None XF86MonBrightnessUp spawn 'light -A 5'
	riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Locking screen with swaylock
riverctl map normal $mod+Shift L spawn "swaylock"

## Set background and border color
riverctl background-color 0xb800ff
riverctl border-color-focused 0xbd93f9
riverctl border-color-unfocused 0x282a36
riverctl border-width 1

## Set repeat rate
riverctl set-repeat 50 300

## auto starting apps
# riverctl spawn "systemctl --user import-environment"
# riverctl spawn "swaybg -i ~/dotfiles/wallpapers/darkest_hour.jpg"
# riverctl spawn "swaybg -i ~/dotfiles/wallpapers/NixOS-1.png"
riverctl spawn "swaybg -i ~/Pictures/Wallpapers/Artix/ArtixPink.png"
riverctl spawn lxpolkit
riverctl spawn waybar
# riverctl spawn /usr/lib/notification-daemon-1.0/notification-daemon
riverctl spawn dunst
# riverctl spawn  "deadd-notification-center"
riverctl spawn "nm-applet --indicator"
riverctl spawn "blueman-applet"
riverctl spawn "emacs --daemon"
# riverctl spawn "redshift -O 5000"
riverctl spawn "fcitx5"
riverctl spawn "/home/ngll/Documents/startpage/autostart.sh"

# Set app-ids of views which should float
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"
riverctl float-filter-add title "zoom"

# Rivertile Defaults
riverctl default-layout rivertile
exec rivertile -main-ratio 0.5
